package com.sms.webservice.soap.impl;
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


import java.util.logging.Logger;


import com.sms.webservice.soap.group.policy.ResponseInfo;
import com.sms.webservice.soap.group.policy.StrategyManagementPlatformService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-06T14:39:31.714+08:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "StrategyManagementPlatformServiceService",
                      portName = "StrategyManagementPlatformService",
                      targetNamespace = "http://strategy.sercice.badsms.ctcc.wsdl.chinatelecom.com.cn",
                      wsdlLocation = "file:/D:/wdsl/StrategyManagementPlatformService.wsdl",
                      endpointInterface = "com.sms.webservice.soap.group.policy.StrategyManagementPlatformService")
                      
public class StrategyManagementPlatformServiceImpl implements StrategyManagementPlatformService {

    private static final Logger LOG = Logger.getLogger(StrategyManagementPlatformServiceImpl.class.getName());

    /* 4.1	省端策略上报业务流程
     * 4、策略生成完成通知(WebService)
     */
    public ResponseInfo getEffectiveStrategyResult(java.lang.String transactionid, java.lang.String filepath) { 
        LOG.info("Executing operation getEffectiveStrategyResult");
        System.out.println(transactionid);
        System.out.println(filepath);
        try {
        	ResponseInfo _return = new ResponseInfo();
            _return.setResult("success");
            _return.setResultdesc("OK");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sms.webservice.soap.group.policy.StrategyManagementPlatformService#setProvincialStrategyBak(java.lang.String provincialpolicysetXml)*
     */
    public ResponseInfo setProvincialStrategyBak(java.lang.String provincialpolicysetXml) { 
        LOG.info("Executing operation setProvincialStrategyBak");
        System.out.println(provincialpolicysetXml);
        try {
            ResponseInfo _return = new ResponseInfo();
            _return.setResult("success");
            _return.setResultdesc("OK");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sms.webservice.soap.group.policy.StrategyManagementPlatformService#getCentralStrategyResult(java.lang.String transactionid)*
     */
    public ResponseInfo getCentralStrategyResult(java.lang.String transactionid) { 
        LOG.info("Executing operation getCentralStrategyResult");
        System.out.println(transactionid);
        try {
        	ResponseInfo _return = new ResponseInfo();
            _return.setResult("success");
            _return.setResultdesc("OK");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sms.webservice.soap.group.policy.StrategyManagementPlatformService#getBlackListResult(java.lang.String transactionid)*
     */
    public ResponseInfo getBlackListResult(java.lang.String transactionid) { 
        LOG.info("Executing operation getBlackListResult");
        System.out.println(transactionid);
        try {
        	ResponseInfo _return = new ResponseInfo();
            _return.setResult("success");
            _return.setResultdesc("OK");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
